import jsPDF from "jspdf";

// Yggdrasil brand colors (RGB for jsPDF)
export const colors = {
  primary: { r: 109, g: 155, b: 109 }, // #6D9B6D sage green
  secondary: { r: 200, g: 138, b: 91 }, // #C88A5B muted orange
  accent: { r: 107, g: 79, b: 64 }, // #6B4F40 earth brown
  background: { r: 254, g: 243, b: 229 }, // #FEF3E5 soft cream
  text: { r: 73, g: 52, b: 38 }, // #493426 deep brown
  textLight: { r: 120, g: 120, b: 120 }, // gray for muted text
};

export const setColor = (doc: jsPDF, color: { r: number; g: number; b: number }) => {
  doc.setTextColor(color.r, color.g, color.b);
};

export const setFillColor = (doc: jsPDF, color: { r: number; g: number; b: number }) => {
  doc.setFillColor(color.r, color.g, color.b);
};

export const addSection = (
  doc: jsPDF,
  title: string,
  yPos: number,
  margin: number = 20
): number => {
  const pageHeight = doc.internal.pageSize.getHeight();
  
  if (yPos > pageHeight - 40) {
    doc.addPage();
    yPos = margin;
  }

  setColor(doc, colors.primary);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(title, margin, yPos);
  
  setColor(doc, colors.text);
  return yPos + 8;
};

export const addBadge = (
  doc: jsPDF,
  text: string,
  x: number,
  y: number,
  bgColor: { r: number; g: number; b: number }
) => {
  const padding = 2;
  const textWidth = doc.getTextWidth(text);
  
  setFillColor(doc, bgColor);
  doc.roundedRect(x, y - 3, textWidth + padding * 2, 5, 1, 1, "F");
  
  doc.setFontSize(8);
  setColor(doc, colors.text);
  doc.text(text, x + padding, y);
};

export const addDivider = (doc: jsPDF, y: number, margin: number = 20) => {
  const pageWidth = doc.internal.pageSize.getWidth();
  doc.setDrawColor(colors.primary.r, colors.primary.g, colors.primary.b);
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageWidth - margin, y);
};

export const checkPageBreak = (
  doc: jsPDF,
  currentY: number,
  requiredSpace: number,
  margin: number = 20
): number => {
  const pageHeight = doc.internal.pageSize.getHeight();
  if (currentY + requiredSpace > pageHeight - margin) {
    doc.addPage();
    return margin;
  }
  return currentY;
};

export const addCoverPage = (
  doc: jsPDF,
  title: string,
  subtitle: string,
  date: string
) => {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const centerX = pageWidth / 2;

  // Background gradient effect with rectangles
  setFillColor(doc, colors.background);
  doc.rect(0, 0, pageWidth, pageHeight, "F");

  // Title
  doc.setFontSize(28);
  doc.setFont("helvetica", "bold");
  setColor(doc, colors.primary);
  doc.text(title, centerX, pageHeight / 2 - 20, { align: "center" });

  // Subtitle
  doc.setFontSize(14);
  doc.setFont("helvetica", "normal");
  setColor(doc, colors.secondary);
  doc.text(subtitle, centerX, pageHeight / 2 + 5, { align: "center" });

  // Date
  doc.setFontSize(11);
  setColor(doc, colors.textLight);
  doc.text(date, centerX, pageHeight / 2 + 20, { align: "center" });

  // Decorative elements
  setColor(doc, colors.accent);
  doc.setLineWidth(1);
  doc.line(centerX - 40, pageHeight / 2 - 30, centerX + 40, pageHeight / 2 - 30);
  doc.line(centerX - 40, pageHeight / 2 + 30, centerX + 40, pageHeight / 2 + 30);

  // Footer
  doc.setFontSize(9);
  setColor(doc, colors.textLight);
  doc.text("Generated by Yggdrasil", centerX, pageHeight - 20, { align: "center" });
};

export const addPageFooter = (doc: jsPDF, pageNum: number) => {
  const pageHeight = doc.internal.pageSize.getHeight();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  doc.setFontSize(8);
  setColor(doc, colors.textLight);
  doc.text(`Page ${pageNum}`, pageWidth - 20, pageHeight - 10, { align: "right" });
  doc.text("Yggdrasil", 20, pageHeight - 10);
};

export const wrapText = (
  doc: jsPDF,
  text: string,
  maxWidth: number,
  x: number,
  y: number,
  lineHeight: number = 5
): number => {
  const lines = doc.splitTextToSize(text, maxWidth);
  let currentY = y;
  
  lines.forEach((line: string) => {
    currentY = checkPageBreak(doc, currentY, lineHeight);
    doc.text(line, x, currentY);
    currentY += lineHeight;
  });
  
  return currentY;
};
