import jsPDF from "jspdf";

// Enhanced Yggdrasil brand colors (RGB for jsPDF)
export const colors = {
  primary: { r: 75, g: 108, b: 75 },      // Deeper forest green
  secondary: { r: 166, g: 124, b: 82 },   // Warmer amber
  accent: { r: 107, g: 79, b: 64 },       // Earth brown
  background: { r: 250, g: 247, b: 242 }, // Warmer cream
  text: { r: 55, g: 42, b: 32 },          // Richer brown
  textLight: { r: 100, g: 90, b: 80 },    // Warmer gray
  highlight: { r: 232, g: 211, b: 185 },  // Section highlight
  spiritual: { r: 128, g: 90, b: 140 },   // Purple for spiritual sections
  success: { r: 72, g: 128, b: 72 },      // Green for completed/positive
  warning: { r: 180, g: 130, b: 70 },     // Orange for warnings
};

export const setColor = (doc: jsPDF, color: { r: number; g: number; b: number }) => {
  doc.setTextColor(color.r, color.g, color.b);
};

export const setFillColor = (doc: jsPDF, color: { r: number; g: number; b: number }) => {
  doc.setFillColor(color.r, color.g, color.b);
};

export const addSection = (
  doc: jsPDF,
  title: string,
  yPos: number,
  margin: number = 25
): number => {
  const pageHeight = doc.internal.pageSize.getHeight();
  
  if (yPos > pageHeight - 40) {
    doc.addPage();
    yPos = margin;
  }

  setColor(doc, colors.primary);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(title, margin, yPos);
  
  setColor(doc, colors.text);
  return yPos + 10;
};

// Enhanced section with decorative header and background
export const addStyledSection = (
  doc: jsPDF,
  title: string,
  _icon: string, // Icon parameter kept for API compatibility but not rendered (emojis don't work in jsPDF)
  yPos: number,
  margin: number = 25
): number => {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  
  if (yPos > pageHeight - 40) {
    doc.addPage();
    yPos = margin;
  }

  // Add subtle background bar
  setFillColor(doc, colors.highlight);
  doc.rect(margin - 5, yPos - 6, pageWidth - margin * 2 + 10, 14, "F");
  
  // Section title (no emoji - jsPDF can't render them)
  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  setColor(doc, colors.primary);
  doc.text(title, margin, yPos + 3);
  
  setColor(doc, colors.text);
  return yPos + 16;
};

export const addBadge = (
  doc: jsPDF,
  text: string,
  x: number,
  y: number,
  bgColor: { r: number; g: number; b: number }
) => {
  const padding = 2;
  const textWidth = doc.getTextWidth(text);
  
  setFillColor(doc, bgColor);
  doc.roundedRect(x, y - 3, textWidth + padding * 2, 5, 1, 1, "F");
  
  doc.setFontSize(8);
  setColor(doc, colors.text);
  doc.text(text, x + padding, y);
};

export const addDivider = (doc: jsPDF, y: number, margin: number = 25) => {
  const pageWidth = doc.internal.pageSize.getWidth();
  doc.setDrawColor(colors.highlight.r, colors.highlight.g, colors.highlight.b);
  doc.setLineWidth(0.8);
  doc.line(margin, y, pageWidth - margin, y);
};

export const checkPageBreak = (
  doc: jsPDF,
  currentY: number,
  requiredSpace: number,
  margin: number = 25
): number => {
  const pageHeight = doc.internal.pageSize.getHeight();
  if (currentY + requiredSpace > pageHeight - margin) {
    doc.addPage();
    return margin;
  }
  return currentY;
};

export const addCoverPage = (
  doc: jsPDF,
  title: string,
  subtitle: string,
  date: string
) => {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const centerX = pageWidth / 2;

  // Background
  setFillColor(doc, colors.background);
  doc.rect(0, 0, pageWidth, pageHeight, "F");

  // Decorative top accent
  setFillColor(doc, colors.primary);
  doc.rect(0, 0, pageWidth, 8, "F");

  // Title
  doc.setFontSize(32);
  doc.setFont("helvetica", "bold");
  setColor(doc, colors.primary);
  doc.text(title, centerX, pageHeight / 2 - 25, { align: "center" });

  // Subtitle
  doc.setFontSize(16);
  doc.setFont("helvetica", "normal");
  setColor(doc, colors.secondary);
  doc.text(subtitle, centerX, pageHeight / 2 + 5, { align: "center" });

  // Date
  doc.setFontSize(12);
  setColor(doc, colors.textLight);
  doc.text(date, centerX, pageHeight / 2 + 25, { align: "center" });

  // Decorative lines
  setColor(doc, colors.accent);
  doc.setLineWidth(1.5);
  doc.line(centerX - 50, pageHeight / 2 - 35, centerX + 50, pageHeight / 2 - 35);
  doc.line(centerX - 50, pageHeight / 2 + 40, centerX + 50, pageHeight / 2 + 40);

  // Footer
  doc.setFontSize(10);
  setColor(doc, colors.textLight);
  doc.text("Generated by Yggdrasil", centerX, pageHeight - 25, { align: "center" });
  
  // Decorative bottom accent
  setFillColor(doc, colors.secondary);
  doc.rect(0, pageHeight - 8, pageWidth, 8, "F");
};

export const addPageFooter = (doc: jsPDF, pageNum: number) => {
  const pageHeight = doc.internal.pageSize.getHeight();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Subtle footer line
  doc.setDrawColor(colors.highlight.r, colors.highlight.g, colors.highlight.b);
  doc.setLineWidth(0.5);
  doc.line(25, pageHeight - 15, pageWidth - 25, pageHeight - 15);
  
  doc.setFontSize(9);
  setColor(doc, colors.textLight);
  doc.text(`Page ${pageNum}`, pageWidth - 25, pageHeight - 8, { align: "right" });
  doc.text("Yggdrasil", 25, pageHeight - 8);
};

export const wrapText = (
  doc: jsPDF,
  text: string,
  maxWidth: number,
  x: number,
  y: number,
  lineHeight: number = 5
): number => {
  const lines = doc.splitTextToSize(text, maxWidth);
  let currentY = y;
  
  lines.forEach((line: string) => {
    currentY = checkPageBreak(doc, currentY, lineHeight);
    doc.text(line, x, currentY);
    currentY += lineHeight;
  });
  
  return currentY;
};

// Helper to add a labeled section with bullet points
export const addBulletList = (
  doc: jsPDF,
  items: string[],
  x: number,
  y: number,
  maxWidth: number,
  bullet: string = "•"
): number => {
  let currentY = y;
  
  items.forEach((item) => {
    currentY = checkPageBreak(doc, currentY, 6);
    doc.text(`${bullet} `, x, currentY);
    currentY = wrapText(doc, item, maxWidth - 10, x + 8, currentY, 5);
  });
  
  return currentY;
};

// Helper for framework icons (returns empty string as jsPDF can't render emojis)
export const getFrameworkIcon = (_framework: string): string => {
  return '';
};

export const getFrameworkName = (framework: string): string => {
  const names: Record<string, string> = {
    'theravada': 'Theravada Buddhism',
    'freudian': 'Psychoanalysis',
    'jungian': 'Jungian Psychology',
    'hermetic': 'Hermeticism',
    'hermeticism': 'Hermeticism',
    'advaita': 'Advaita Vedanta',
    'advaita_vedanta': 'Advaita Vedanta',
    'taoist': 'Taoism',
    'taoism': 'Taoism',
  };
  return names[framework.toLowerCase()] || framework;
};
